"use client";

import * as React from "react";
import { motion } from "framer-motion";
import { Badge } from "@/components/ui/badge";
import { FileText, ArrowLeft, Scale, ShieldAlert, Cpu } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function TermsPage() {
  return (
    <div className="flex flex-col gap-12 md:gap-16 pt-32 pb-24 relative overflow-hidden">
      {/* Background Glow */}
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -z-10 w-[500px] h-[500px] rounded-full bg-accent/5 blur-[120px]" />

      <section className="container mx-auto px-4 md:px-6 max-w-4xl flex flex-col gap-6 text-center">
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="mx-auto"
        >
          <Badge className="bg-accent/10 border-accent/20 text-accent rounded-full px-3 py-1 text-xs font-semibold flex items-center gap-1 w-fit">
            <Scale className="w-3.5 h-3.5" /> Legal & Governance
          </Badge>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="text-3xl sm:text-4xl md:text-5xl font-extrabold tracking-tight font-heading leading-tight"
        >
          Terms of Service
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="text-muted-foreground text-sm max-w-xl mx-auto"
        >
          Last updated: June 3, 2026. Please read these Terms of Service carefully before utilizing the scoping tools and scheduling consulting hours.
        </motion.p>
      </section>

      <section className="container mx-auto px-4 md:px-6 max-w-3xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="flex flex-col gap-8 text-left"
        >
          {/* Back link */}
          <Button asChild variant="ghost" className="w-fit -ml-2 text-xs text-muted-foreground hover:text-white rounded-full">
            <Link href="/" className="flex items-center gap-1.5">
              <ArrowLeft className="w-3.5 h-3.5" /> Back to Home
            </Link>
          </Button>

          {/* Terms content */}
          <div className="prose prose-invert max-w-none text-xs text-muted-foreground leading-relaxed flex flex-col gap-6">
            <div className="flex flex-col gap-2">
              <h2 className="text-base font-bold text-white uppercase tracking-wider border-b border-white/10 pb-2">1. Agreement to Terms</h2>
              <p>
                By accessing this website, utilizing our interactive CPMAI-style AI Scoper, or scheduling strategy meetings, you agree to be bound by these Terms of Service, all applicable regional laws, and database safety protocols. If you do not agree to these terms, you are restricted from utilizing the scoping tools.
              </p>
            </div>

            <div className="flex flex-col gap-2">
              <h2 className="text-base font-bold text-white uppercase tracking-wider border-b border-white/10 pb-2">2. Scoper Input Restrictions & Code Safety</h2>
              <p>
                When utilizing the CPMAI Scoper or submitting inquiries:
              </p>
              <ul className="list-disc pl-5 flex flex-col gap-1.5 mt-2">
                <li>You are strictly prohibited from submitting active malware, malicious code commands, SQL injection payloads, or copyrighted assets that you do not own.</li>
                <li>Inputs must describe legitimate corporate scoping goals. Automated scripts, bots, and spam submissions will be blocked from accessing our serverless routes.</li>
              </ul>
            </div>

            <div className="flex flex-col gap-2">
              <h2 className="text-base font-bold text-white uppercase tracking-wider border-b border-white/10 pb-2">3. Proprietary Intellectual Property</h2>
              <p>
                All elements of the Indusnet AI digital platform—including layout variables, cosmic CSS styling, visual interactive designs, custom timelines, and the CPMAI Scoper frontend components—are the exclusive intellectual property of **Indusnet Technologies Ltd.** and are protected under international copyright regulations.
              </p>
            </div>

            <div className="flex flex-col gap-2">
              <h2 className="text-base font-bold text-white uppercase tracking-wider border-b border-white/10 pb-2">4. Disclaimers & Limits of Scoping Estimates</h2>
              <p>
                All project recommendations, resource sizing, hardware budgets, and integration checklists generated by the CPMAI scoping tool:
              </p>
              <ul className="list-disc pl-5 flex flex-col gap-1.5 mt-2">
                <li>Are preliminary evaluations representing structural suggestions, not binding financial quotes.</li>
                <li>Actual engineering scopes are subject to direct developer reviews and formal statements of work (SOW) executed by Indusnet AI Solutions Architects.</li>
              </ul>
            </div>

            <div className="flex flex-col gap-2">
              <h2 className="text-base font-bold text-white uppercase tracking-wider border-b border-white/10 pb-2">5. Updates and Governing Jurisdictions</h2>
              <p>
                Indusnet AI reserves the right to modify these terms. Continued usage of the platforms after updates constitutes explicit approval of modifications. These terms are governed and construed in accordance with the corporate laws of India under registered headquarters frameworks.
              </p>
            </div>
          </div>
        </motion.div>
      </section>
    </div>
  );
}
